### ISSUE TITLE
Use last stop as "zuletzt gesehen" instead of destination_station

### ISSUE THREAD

**Issue by AdriDevelopsThings** [regenbogen-ice/frontend#9]
Maybe the train will stop a few stations ahead the destination_station and the other stations will be cancelled. The problem is that the frontend shows the `destination_station` parameter. Maybe the website should display "Zuletzt gesehen als xy in" with the last not cancelled station. So the code should be modified in this way:

`trips[0].destination_station` -> `trips[0].stops.filter(stop => !stop.cancelled).pop().station`

**Comment by PhilippIRL** [comment]
Or maybe just fix the API?
